### ISSUE TITLE
slow compared to spconv 

### ISSUE THREAD

**Issue by buaaJeremyduan** [StanfordVL/MinkowskiEngine#22] opened 2019-08-10 06:38 UTC
I build the same model using spconv and MinkowskiEngine. 
self.middle_conv = nn.Sequential(
            MinkowskiConvolution(num_input_features, 16, kernel_size=3, dimension=3),
            MinkowskiBatchNorm(16),
            MinkowskiReLU(),
            MinkowskiConvolution(16, 16, kernel_size=3, dimension=3),
            MinkowskiBatchNorm(16),
            MinkowskiReLU(),
            MinkowskiConvolution(16, 32, kernel_size=3, stride=2, dimension=3),
            MinkowskiBatchNorm(32),
            MinkowskiReLU(),
            MinkowskiConvolution(32, 32, kernel_size=3, dimension=3),
            MinkowskiBatchNorm(32),
            MinkowskiReLU(),
            MinkowskiConvolution(32, 32, kernel_size=3, dimension=3),
            MinkowskiBatchNorm(32),
            MinkowskiReLU(),
            MinkowskiConvolution(32, 64, kernel_size=3, stride=2, dimension=3),
            MinkowskiBatchNorm(64),
            MinkowskiReLU(),
            MinkowskiConvolution(64, 64, kernel_size=3, dimension=3),
            MinkowskiBatchNorm(64),
            MinkowskiReLU(),
            MinkowskiConvolution(64, 64, kernel_size=3, dimension=3),
            MinkowskiBatchNorm(64),
            MinkowskiReLU(),
            MinkowskiConvolution(64, 64, kernel_size=3, dimension=3),
            MinkowskiBatchNorm(64),
            MinkowskiReLU(),
            MinkowskiConvolution(64, 64, kernel_size=3, stride=2, dimension=3),
            MinkowskiBatchNorm(64),
            MinkowskiReLU(),
            MinkowskiConvolution(64, 64, kernel_size=3, dimension=3),
            MinkowskiBatchNorm(64),
            MinkowskiReLU(),
            MinkowskiConvolution(64, 64, kernel_size=3, dimension=3),
            MinkowskiBatchNorm(64),
            MinkowskiReLU(),
            MinkowskiConvolution(64, 64, kernel_size=3, dimension=3),
            MinkowskiBatchNorm(64),
            MinkowskiReLU(),
            MinkowskiConvolution(64, 64, kernel_size=(3,1,1), stride=(2,1,1), dimension=3),
            MinkowskiBatchNorm(64),
            MinkowskiReLU(),
        )
and measure the time. The spconv one is about 0.2s, however, the minkowskiengine is about 3s. Is that normal?

**Comment by chrischoy** [comment] 2019-08-10 07:04
Thanks for reporting the issue. I suspect a couple of recent updates to be the cause, but I would like to know the self-contained snippet to reproduce the case. Could you share more detail? Thanks!

**Comment by buaaJeremyduan** [comment] 2019-08-10 08:11
Cloud you give me your emal address? I could send you test data and code.

**Comment by chrischoy** [comment] 2019-08-10 08:44
It’s chrischoy at stanford dot edu.

**Comment by chrischoy** [comment] 2019-08-19 15:54
Well, the code that you gave me returns

```
[  41 1600 1408]
spconv time is  0.729060173034668
Setting the ME of dimension 3 number of threads to 8
mink middle time is  1.3128294944763184
```

On my GTX1060 with Intel i7-7700HQ CPU @ 2.80GHz.
Currently, the MinkowskiEngine uses a cpu hashtable based on the google-sparsehash, which is quite the bottleneck right now, but will be resolved in the future.

But, thanks for the pointer.

**Comment by chrischoy** [comment] 2019-08-27 10:59
After closer look, the code actually generates a dense grid for indexes. This is a lot faster, but would be problematic for high-dimensional spaces or spaces with large volumes.

It seems like a problem dependent and if you care about low-dimensional spaces with limited volume, this could be a good option, but for large unbounded space, you should opt for methods that actually creates a hash table rather than a dense grid.

**Comment by chrischoy** [comment] 2019-08-28 19:48
Currently the version 0.2.6 gives the following result

```
spconv time is  0.4891397953033447
mink middle time is  0.5238840579986572
```

**Comment by chrischoy** [comment] 2019-09-05 09:20
Closing it for no updates.

**Closed by chrischoy** 2019-09-05 09:20 UTC

**Comment by turboxin** [comment] 2020-04-16 08:46
Hi @buaaJeremyduan，apart from the speed, have you compared the results after replacing spconv with MinkowskiEngine? Looking forward to your reply~ Thank you

**Comment by buaaJeremyduan** [comment] 2020-04-19 03:05
I have not compared the result.
